name: shellcmd #workflow name

on: [push] #event

jobs: 
  run-shell-command: #job name
    runs-on: ubuntu-latest #runner
    #steps
    steps: 
      - name: echo a string
        run: echo "Hello world"
      - name: multi line script
        run: |
            node -v
            npm -v 